const imageMapping = {
    "Veg Biryani": "/images/veg-biryani.jpg",
    "Ch Curry Baghara Rice": "/images/curry-baghara-rice.jpg",
    "Ch Tandoori Biryani": "/images/tandoori-biryani.jpg",
    "Chicken 65 Biryani": "/images/chicken-65-biryani.jpg",
    "Fry Piece biryani": "/images/fry-piece-biryani.jpg",
    "Dum Biryani": "/images/dum-biryani.jpg",
    "Water Bottle": "/images/water-bottle.jpg",
    "Ice Peach Tea": "/images/ice-peach-tea.jpg",
    "Oreo Milkshake": "/images/oreo-milkshake.jpg",
    "Mango Lassi": "/images/mango-lassi.jpg",
    "Mango Milkshake": "/images/mango-milkshake.jpg",
    "Jeera Soda": "/images/jeera-soda.jpg",
    "Frooti Bottle": "/images/frooti.jpg",
    "Thums Up": "/images/thums up.jpg",
    "Coke": "/images/coke.jpg",
    "Chilli Chicken": "/images/chilli-chicken.jpg",
    "Chicken 65": "/images/chicken-65.jpg",
    "Vada": "/images/vada.jpg",
    "Uttapam": "/images/uttapam.jpg",
    "Idly": "/images/idly.jpg",
    "Brownie": "/images/brownie.jpg",
    "Rasagulla": "/images/rasagulla.jpg",
    "Gulab Jamun": "/images/gulab-jamun.jpg",
    "Rusk": "/images/rusk.jpg",
    "Chai Biscuit": "/images/chai-biscuit.jpg",
    "Moms Magic": "/images/moms-magic.jpg",
    "Parle G": "/images/parle-g.jpg",
    "Dahi Puri": "/images/dahi-puri.jpg",
    "Pani Puri": "/images/pani-puri.jpg",
    "Vada Pav": "/images/vada-pav.jpg",
    "Samosa Chat": "/images/samosa-chat.jpg",
    "Pav Bhaji": "/images/pav-bhaji.jpg",
    "Cut Mirchi": "/images/cut-mirchi.jpg",
    "Punugulu": "/images/punugulu.jpg",
    "Small Coffee": "/images/small-coffee.jpg",
    "Large Chai": "/images/large-chai.jpg",
    "Medium Chai": "/images/medium-chai.jpg",
    "Small Chai": "/images/small-chai.jpg"
  };
  
  export default imageMapping;
  