const imageMapping = {
    "Veg Biryani": "/images/veg-biryani.jpg",
    "Ch Curry Baghara Rice": "/images/curry-baghara-rice.jpg",
    "Ch Tandoori Biryani": "/images/tandoori-biryani.jpg",
    "Chicken 65 Biryani": "/images/chicken-65-biryani.jpg",
    "Fry Piece biryani": "/images/fry-piece-biryani.jpg",
    "Dum Biryani": "/images/dum-biryani.jpg",
    "Water Bottle": "/images/water-bottle.jpg",
    "Ice Peach Tea": "/images/ice-peach-tea.jpg",
    "Oreo Milkshake": "/images/oreo-milkshake.jpg",
    "Mango Lassi": "/images/mango-lassi.jpg",
    "Mango Milkshake": "/images/mango-milkshake.jpg",
    "Jeera Soda": "/images/jeera-soda.jpg",
    "Frooti Bottle": "/images/frooti.jpg",
    "Thums Up": "/images/thums-up.jpg",
    "Coke": "/images/coke.jpg",
    "Chilli Chicken": "/images/chilli-chicken.jpg",
    "Chicken 65": "/images/chicken-65.jpg",
    "Vada": "/images/vada.jpg",
    "Uttapam": "/images/uttapam.jpg",
    "Idli": "/images/idli.jpg",
    "Brownie": "/images/brownie.jpg",
    "Rasagulla": "/images/rasagulla.jpg",
    "Gulab Jamun": "/images/gulab-jamun.jpg",
    "Rusk": "/images/rusk.jpg",
    "Chai Biscuit": "/images/chai-biscuit.jpg",
    "Moms Magic": "/images/moms-magic.jpg",
    "Parle G": "/images/parle-g.jpg",
    "Dahi Puri": "/images/dahi-puri.jpg",
    "Pani Puri": "/images/pani-puri.jpg",
    "Vada Pav": "/images/vada-pav.jpg",
    "Samosa Chat": "/images/samosa-chat.jpg",
    "Pav Bhaji": "/images/pav-bhaji.jpg",
    "Cut Mirchi": "/images/cut-mirchi.jpg",
    "Punugulu": "/images/punugulu.jpg",
    "Small Coffee": "/images/small-coffee.jpg",
    "Large Chai": "/images/large-chai.jpg",
    "Medium Chai": "/images/medium-chai.jpg",
    "Small Chai": "/images/small-chai.jpg",
    "Plain Dosa": "/images/plain-dosa.jpg",
    "Fanta": "/images/fanta.jpg",
    "Cold Coffee": "/images/cold-coffee.jpg",
    "Strawberry Milkshake": "/images/strawberry-milkshake.jpg",
    "Banana Milkshake": "/images/banana-milkshake.jpg",
    "Chocolate Milkshake": "/images/chocolate-milkshake.jpg",
    "Chilli Paneer": "/images/chilli-paneer.jpg",
    "Veg Manchurian": "/images/veg-manchurian.jpg",
    "Gobi 65": "/images/gobi-65.jpg",
    "Crispy Corn": "/images/crispy-corn.jpg",
    "Chicken Majestic": "/images/chicken-majestic.jpg",
    "Chicken Pakodi": "/images/chicken-pakodi.jpg",
    "Malai Bun": "/images/malai-bun.jpg",
    "Maska Bun": "/images/maska-bun.jpg",
    "Samosa": "/images/samosa.jpg",
    "Papidi Chat":"/images/papidi-chat.jpg",
    "Bhel Puri":"/images/bhel-puri.jpg",
    "Aloo Bajji":"/images/aloo-bajji.jpg",
    "Egg Bajji":"/images/egg-bajji.jpg",
    "Onion Pakodi":"/images/onion-pakodi.jpg",
    "Bread Omlette":"/images/bread-omlette.jpg",
    "Boost":"/images/boost.jpg",
    "Horlicks":"/images/horlicks.jpg",
    "Hot Chocolate":"/images/hot-chocolate.jpg",
   "Onion Dosa":"/images/onion-dosa.jpg",
   "Ghee Karam Dosa":"/images/ghee-karam-dosa.jpg",
   "Paneer Dosa": "/images/paneer-dosa.jpg",
   "Mini Podi Dosa 2pc":"/images/mini-podi-dosa-2pc.jpg",
   "Bangalore Dosa":"/images/bangalore-dosa.jpg",
   "Sambar Idli":"/images/sambar-idli.jpg",
   "Plain Vada":"/images/plain-vada.jpg",
   "Plain Idli": "/images/plain-idli.jpg",
   "Spot Idli": "/images/spot-idli.jpg",
   "Ghee Podi Idli": "/images/ghee-podi-idli.jpg",
   "Sambar Vada": "/images/sambar-vada.jpg",
   "Ponganalu": "/images/ponganalu.jpg",
   "Veg Noodles": "/images/veg-noodles.jpg",
   "Chicken Noodles": "/images/chicken-noodles.jpg",
   "Egg Noodles": "/images/egg-noodles.jpg",
   "Veg Fried Rice": "/images/veg-fried-rice.jpg",
   "Egg Fried Rice": "/images/egg-fried-rice.jpg",
   "Chicken Fried Rice": "/images/chicken-fried-rice.jpg",
   "Paneer Fried Rice": "/images/paneer-fried-rice.jpg",
   "Maggie": "/images/maggie.jpg",
   "Masala Dosa": "/images/masala-dosa.jpg",
   "Egg Dosa": "/images/egg-dosa.jpg",
   "Pancakes": "/images/pancakes.jpg",
   "Nimbu Soda": "/images/nimbu-soda.jpg",
   "Potato Twist": "/images/potato-twist.jpg",
   "Chicken Dosa": "/images/chicken-dosa.jpg",
   "Kaima Idli": "/images/kaima-idli.jpg",
   "Purani-Dilli": "/images/purani-dilli.jpg"
  };
  
  export default imageMapping;
  