import { IMAGE_BASE } from "../services/imageBase";

const imageMapping = {
  "Veg Biryani": `${IMAGE_BASE}/images/veg-biryani.jpg`,
  "Ch Curry Baghara Rice": `${IMAGE_BASE}/images/curry-baghara-rice.jpg`,
  "Ch Tandoori Biryani": `${IMAGE_BASE}/images/tandoori-biryani.jpg`,
  "Chicken 65 Biryani": `${IMAGE_BASE}/images/chicken-65-biryani.jpg`,
  "Fry Piece biryani": `${IMAGE_BASE}/images/fry-piece-biryani.jpg`,
  "Dum Biryani": `${IMAGE_BASE}/images/dum-biryani.jpg`,
  "Water Bottle": `${IMAGE_BASE}/images/water-bottle.jpg`,
  "Ice Peach Tea": `${IMAGE_BASE}/images/ice-peach-tea.jpg`,
  "Oreo Milkshake": `${IMAGE_BASE}/images/oreo-milkshake.jpg`,
  "Mango Lassi": `${IMAGE_BASE}/images/mango-lassi.jpg`,
  "Mango Milkshake": `${IMAGE_BASE}/images/mango-milkshake.jpg`,
  "Jeera Soda": `${IMAGE_BASE}/images/jeera-soda.jpg`,
  "Frooti Bottle": `${IMAGE_BASE}/images/frooti.jpg`,
  "Thums Up": `${IMAGE_BASE}/images/thums-up.jpg`,
  "Coke": `${IMAGE_BASE}/images/coke.jpg`,
  "Chilli Chicken": `${IMAGE_BASE}/images/chilli-chicken.jpg`,
  "Chicken 65": `${IMAGE_BASE}/images/chicken-65.jpg`,
  "Vada": `${IMAGE_BASE}/images/vada.jpg`,
  "Uttapam": `${IMAGE_BASE}/images/uttapam.jpg`,
  "Idli": `${IMAGE_BASE}/images/idli.jpg`,
  "Brownie": `${IMAGE_BASE}/images/brownie.jpg`,
  "Rasagulla": `${IMAGE_BASE}/images/rasagulla.jpg`,
  "Gulab Jamun": `${IMAGE_BASE}/images/gulab-jamun.jpg`,
  "Rusk": `${IMAGE_BASE}/images/rusk.jpg`,
  "Chai Biscuit": `${IMAGE_BASE}/images/chai-biscuit.jpg`,
  "Moms Magic": `${IMAGE_BASE}/images/moms-magic.jpg`,
  "Parle G": `${IMAGE_BASE}/images/parle-g.jpg`,
  "Dahi Puri": `${IMAGE_BASE}/images/dahi-puri.jpg`,
  "Pani Puri": `${IMAGE_BASE}/images/pani-puri.jpg`,
  "Vada Pav": `${IMAGE_BASE}/images/vada-pav.jpg`,
  "Samosa Chat": `${IMAGE_BASE}/images/samosa-chat.jpg`,
  "Pav Bhaji": `${IMAGE_BASE}/images/pav-bhaji.jpg`,
  "Cut Mirchi": `${IMAGE_BASE}/images/cut-mirchi.jpg`,
  "Punugulu": `${IMAGE_BASE}/images/punugulu.jpg`,
  "Small Coffee": `${IMAGE_BASE}/images/small-coffee.jpg`,
  "Large Chai": `${IMAGE_BASE}/images/large-chai.jpg`,
  "Medium Chai": `${IMAGE_BASE}/images/medium-chai.jpg`,
  "Small Chai": `${IMAGE_BASE}/images/small-chai.jpg`,
  "Plain Dosa": `${IMAGE_BASE}/images/plain-dosa.jpg`,
  "Fanta": `${IMAGE_BASE}/images/fanta.jpg`,
  "Cold Coffee": `${IMAGE_BASE}/images/cold-coffee.jpg`,
  "Strawberry Milkshake": `${IMAGE_BASE}/images/strawberry-milkshake.jpg`,
  "Banana Milkshake": `${IMAGE_BASE}/images/banana-milkshake.jpg`,
  "Chocolate Milkshake": `${IMAGE_BASE}/images/chocolate-milkshake.jpg`,
  "Chilli Paneer": `${IMAGE_BASE}/images/chilli-paneer.jpg`,
  "Veg Manchurian": `${IMAGE_BASE}/images/veg-manchurian.jpg`,
  "Gobi 65": `${IMAGE_BASE}/images/gobi-65.jpg`,
  "Crispy Corn": `${IMAGE_BASE}/images/crispy-corn.jpg`,
  "Chicken Majestic": `${IMAGE_BASE}/images/chicken-majestic.jpg`,
  "Chicken Pakodi": `${IMAGE_BASE}/images/chicken-pakodi.jpg`,
  "Malai Bun": `${IMAGE_BASE}/images/malai-bun.jpg`,
  "Maska Bun": `${IMAGE_BASE}/images/maska-bun.jpg`,
  "Samosa": `${IMAGE_BASE}/images/samosa.jpg`,
  "Papidi Chat": `${IMAGE_BASE}/images/papidi-chat.jpg`,
  "Bhel Puri": `${IMAGE_BASE}/images/bhel-puri.jpg`,
  "Aloo Bajji": `${IMAGE_BASE}/images/aloo-bajji.jpg`,
  "Egg Bajji": `${IMAGE_BASE}/images/egg-bajji.jpg`,
  "Onion Pakodi": `${IMAGE_BASE}/images/onion-pakodi.jpg`,
  "Bread Omlette": `${IMAGE_BASE}/images/bread-omlette.jpg`,
  "Boost": `${IMAGE_BASE}/images/boost.jpg`,
  "Horlicks": `${IMAGE_BASE}/images/horlicks.jpg`,
  "Hot Chocolate": `${IMAGE_BASE}/images/hot-chocolate.jpg`,
  "Onion Dosa": `${IMAGE_BASE}/images/onion-dosa.jpg`,
  "Ghee Karam Dosa": `${IMAGE_BASE}/images/ghee-karam-dosa.jpg`,
  "Paneer Dosa": `${IMAGE_BASE}/images/paneer-dosa.jpg`,
  "Mini Podi Dosa 2pc": `${IMAGE_BASE}/images/mini-podi-dosa-2pc.jpg`,
  "Bangalore Dosa": `${IMAGE_BASE}/images/bangalore-dosa.jpg`,
  "Sambar Idli": `${IMAGE_BASE}/images/sambar-idli.jpg`,
  "Plain Vada": `${IMAGE_BASE}/images/plain-vada.jpg`,
  "Plain Idli": `${IMAGE_BASE}/images/plain-idli.jpg`,
  "Spot Idli": `${IMAGE_BASE}/images/spot-idli.jpg`,
  "Ghee Podi Idli": `${IMAGE_BASE}/images/ghee-podi-idli.jpg`,
  "Sambar Vada": `${IMAGE_BASE}/images/sambar-vada.jpg`,
  "Ponganalu": `${IMAGE_BASE}/images/ponganalu.jpg`,
  "Veg Noodles": `${IMAGE_BASE}/images/veg-noodles.jpg`,
  "Chicken Noodles": `${IMAGE_BASE}/images/chicken-noodles.jpg`,
  "Egg Noodles": `${IMAGE_BASE}/images/egg-noodles.jpg`,
  "Veg Fried Rice": `${IMAGE_BASE}/images/veg-fried-rice.jpg`,
  "Egg Fried Rice": `${IMAGE_BASE}/images/egg-fried-rice.jpg`,
  "Chicken Fried Rice": `${IMAGE_BASE}/images/chicken-fried-rice.jpg`,
  "Paneer Fried Rice": `${IMAGE_BASE}/images/paneer-fried-rice.jpg`,
  "Maggie": `${IMAGE_BASE}/images/maggie.jpg`,
  "Masala Dosa": `${IMAGE_BASE}/images/masala-dosa.jpg`,
  "Egg Dosa": `${IMAGE_BASE}/images/egg-dosa.jpg`,
  "Pancakes": `${IMAGE_BASE}/images/pancakes.jpg`,
  "Nimbu Soda": `${IMAGE_BASE}/images/nimbu-soda.jpg`,
  "Potato Twist": `${IMAGE_BASE}/images/potato-twist.jpg`,
  "Chicken Dosa": `${IMAGE_BASE}/images/chicken-dosa.jpg`,
  "Kaima Idli": `${IMAGE_BASE}/images/kaima-idli.jpg`,
  "Purani-Dilli": `${IMAGE_BASE}/images/purani-dilli.jpg`,
  "Poori": `${IMAGE_BASE}/images/poori.jpg`,
};

export default imageMapping;
